### ISSUE TITLE
Has anyone actually been able to get this to work?

### ISSUE THREAD

**Issue by weatherston** [olup/kobowriter#13]
Short of creating a development environment, I have tried this on several kobo devices and it either bricks the device or, more commonly, the Kobowriter just does not open. 
So, copying the KoboRoot.tar.gz file to the kobo; bricked my aura (I knew the risk and am ok but sad), does not respond on my touch (several keyboards and power supplies and power on sequences), and I am waiting for a glow to arrive to try it.
This function is so useful that I started to look into learning the Go (Golang) programming language. I would rather be writing my novels than learning to code but the possibility of days worth of battery live in a distraction free environment is attractive. 
A device that accepts text on an e-ink screen, saves the results, and allows extraction of those text files is selling for six times what a kobo is selling for. If this is possible with a kobo please tell me how to do it. I have a blank computer that I can add a developmental environment to, I just need to know how. Any help would be appreciated. Give me a fish or teach me to fish. I am all ears.
It is just sad now that I don't have a device to read on, now that my reader is bricked, and nothing to write on.

**Comment by badrihippo** [comment]
Hi @weatherston I'm trying to get it working on my device too (I have a working Touch and a half-broken Nia). But what model of Aura do you have? If it's one with a removable SD card you may still be able to burn back the original image and make your device usable.

**Comment by sQur1** [comment]
> Hi @weatherston I'm trying to get it working on my device too (I have a working Touch and a half-broken Nia). But what model of Aura do you have? If it's one with a removable SD card you may still be able to burn back the original image and make your device usable.

Is there documentation around on how to backup the original image and flash it back on?

**Comment by badrihippo** [comment]
You can check on [the Mobileread forums](https://mobileread.com/), but basically if your device has a removable SD card, you can remove it, plug it into your computer directly (using an SD card reader), and burn the image on top. You will have to download the image from somewhere, depending on your device model (hint: ask on the Mobileread forums).

For flashing, I'm on Linux (Manjaro) so I just use the command:

```sh
dd if=/path/to/image of=/dev/name-of-sdcard status=progress
```

Replace `/path/to/image` with the path to your downloaded image and `/name-of-sdcard` with the device ID of your SD card, such as `sdc`. **Warning: choosing the wrong device will cause you to lose data. For example if you accidentally flash onto one of your own hard-drive partitions, the data on that partition will get lost!**

For other operating systems, the usage may vary.

(By the way, if you have a working Kobo, you can create your own backup image by `dd`ing the other way, from the SD card to a local file. Then, if something goes wrong, just `dd` it back and you'll have your files and settings and everything intact as well).

**Comment by weatherston** [comment]
My Aura is the model with a removable SD drive. I was sent a copy of the SD flash from someone on the Mobileread forums and sent this like https://www.mobileread.com/forums/showthread.php?t=209122 directing me on how to install it. 
Unfortunately, when I tried to get the card out my fat fingers and poor eyesight caused me to do some damage to the interior. I am sure the process from the forum would have worked.

**Comment by badrihippo** [comment]
Oh no! Is it only the SD card that's damaged or the device itself? (If it's just the card you can simply replace it with a new SD card, but from your description I fear it's not the case...)

**Comment by weatherston** [comment]
Yes, unfortunately it was the prongs where the power plugs in that became damaged. Maybe if I had a very small soldering iron I could fix it but I don't. I did end up picking up an old touch for a couple bucks so that I can keep reading. It was my own fault for braking it. I assumed that it was a good idea to disconnect the power while playing with the innards but it was probably unnecessary to just remove the SD card.

**Comment by badrihippo** [comment]
Oh well. I'm glad you got the Touch! It's what I'm using right now too; it's served me well for ten years and counting and is still getting regular updates. So your reading is in good hands :slightly_smiling_face:
