### ISSUE TITLE
It works too on kindle ?

### ISSUE THREAD

**Issue by filirnd** [olup/kobowriter#2]
Hi I like so much your project but I've a Kindle 8th gen (base model). Do you think that your guide/sw works on ? I've seen that the koxtoolchain supports kindle devices. Have you some ideas about ?

Thank you in advance

**Comment by olup** [comment]
Koxtoolchain and FBINK will work nicely on kindle. 

But the main problem would be to plug a keyboard in your device. I can't find any info about OTG support in your kindle, there is however a start of a topic on https://www.mobileread.com/forums/showthread.php?t=333930, but I don't know much about kindle in general, so it is still a big maybe.

**Comment by filirnd** [comment]
Thank you for your hints. If I?ll found some of interesting things and them works I'll reply to this issue.
